name: Fix PR

on:
  pull_request:

jobs:
  lint-fix:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PR_FIXER }}
          ref: ${{ github.head_ref }}
      - uses: wyvox/action-setup-pnpm@v3

      ###################################################
      # Commit easily fixable things back to the branch
      ###################################################
      - run: pnpm lint:fix
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Automatically run 'pnpm lint:fix'"
          branch: ${{ github.head_ref }}

