# Because this library needs to be built,
# we can't easily point package.json files at the git repo for easy cross-repo testing.
#
# This workflow brings back that capability by placing the compiled assets on a "dist" branch
# (configurable via the "branch" option below)
name: Push dist

on:
  push:
    branches:
      - main
      - master
  pull_request: {}

jobs:
  push-dist:
    name: Push dist
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: NullVoxPopuli/action-setup-pnpm@v2
      - uses: kategengler/put-built-npm-package-contents-on-branch@v2.0.0
        with:
          branch: dist-${{ github.ref_name }}
          token: ${{ secrets.GITHUB_TOKEN }}
          working-directory: reactiveweb

      - name: Create comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: 1
          body: |
            This branch can be tried locally via updating package.json to:
            ```
            "reactiveweb": "github:NullVoxPopuli/reactiveweb#dist-${{ github.ref_name }}",
            ```
